### PR TITLE
Code Update --> Vaibhavraj Nath Chauhan

### LINKED ISSUE #1: Gamora's Switchblade
In the [`Gamora_switchblade.cpp`](https://github.com/GDSC-Techno/Save-the-world/blob/main/MARVEL/Gamora_switchblade.cpp) file, Gamora's switchblade looks like this :

fest21_11-copy

Modify the code and complete her blade to look like so : 

fest21_12-copy

##### Last but not the least, Gamora's actual switchblade 🤩 

switchblade_gamora

### PR DESCRIPTION
**Pull request by vaibhavraj-nath-chauhan**

### CODE REVIEW

**Comment by jkugsiya** [comment]
Hey @Vaibhavraj-nath-chauhan you should've first gotten an issue assigned then only you should work! This is because no two people work on the same issue.

**Comment by vaibhavraj-nath-chauhan** [comment]
I dont have any idea how to do that

**Comment by jkugsiya** [comment]
> I dont have any idea how to do that

No problem @Vaibhavraj-nath-chauhan. First, go to the issue you want to work on and comment there that you would like to work on that problem then the maintainer or member of that repo will assign that to you. This is how it works, let me know if you need further help.

**Comment by vaibhavraj-nath-chauhan** [comment]
So, for this issue, I am not eligible.

**Comment by jkugsiya** [comment]
> So, for this issue, I am not eligible.

There is nothing like eligibility. You can still get assigned, just follow the steps I mentioned and I'll review your code and merge if all is good.

**Comment by jkugsiya** [comment]
@Vaibhavraj-nath-chauhan Reviewed your code and it LGTM!

**Pull request merged**
